services:
  krk:
      image: 'krk-apartments'
      ports:
        - "8080:8080"
    #  restart: always
      depends_on:
        postgresql:
          condition: service_healthy
      environment:
          - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/krkapartments
          - SPRING_DATASOURCE_USERNAME=postgres
          - SPRING_DATASOURCE_PASSWORD=password
          - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  payment:
      image: 'payment-service'
      ports:
      - "8100:8100"
     # restart: always
      depends_on:
        postgresql:
          condition: service_healthy
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/krkapartments
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=password
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  frontend:
      container_name: krk-apartments-frontend
      build: ./krk-apartments-frontend
      volumes:
        - "./s:/krk-apartments/krk-apartments-frontend/src"
        - "./s:/krk-apartments/krk-apartments-frontend/node_modules"
      ports:
        - "3000:3000"
      stdin_open: true
      environment:
        - CHOKIDAR_USEPOLLING=true
      command: npm start


  postgresql:
      image: 'postgres'
      hostname: postgresql
      restart: always
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
      ports:
      - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_USER=postgres
        - POSTGRES_DB=krkapartments
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5

#  liquibase:
#      build: .
#      image: liquibase/liquibase
##      depends_on:
##        postgresql:
##          condition: service_healthy
#      volumes:
#        - ./krk-apartments/src/main/resources/liquibase-changeLog.xml:/liquibase/liquibase-changeLog.xml
#        - ./krk-apartments/src/main/resources/database_init:/liquibase/database_init
#      command: --changeLogFile=liquibase-changeLog.xml --url=jdbc:postgresql://postgresql:5432/krkapartments --username=postgres --password=password update

#      environment:
#        - POSTGRES_HOST=postgresql
#        - LIQUIBASE_PASSWORD=password
#        - LIQUIBASE_USER=postgres
#        - LIQUIBASE_DB=krkapartments
#        - LIQUIBASE_CHANGELOG=./krk-apartments/src/main/resources/liquibase-changeLog.xml
#        - LIQUIBASE_URL=jdbc:postgresql://postgresql:5432/krkapartments
